#Variables to control makefile operation

CXX = g++
CXXFLAGS = -Wall -g

#Targets
main: main.o Game.o Movie.o Functions.o
	$(CXX) $(CXXFLAGS) -o main main.o Game.o Movie.o Functions.o

main.o: main.cpp Game.h Movie.h Functions.h
	$(CXX) $(CXXFLAGS) -o main.cpp

Game.o: Game.h

Movie.o: Movie.h

Functions.o: Game.h Movie.h Functions.h